name: cargo-semver-checks
on:
  pull_request: { paths: ['**/Cargo.toml'] }
  workflow_dispatch:
jobs:
  semver-checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: obi1kenobi/cargo-semver-checks-action@v2
