name: Cargo Machete

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete

      - name: Run cargo machete
        run: cargo machete .
