on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: Fuzzing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




permissions:
  contents: read

jobs:
  cargo-fuzz:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Rust
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz || true
      - name: Run fuzzing
        run: cargo fuzz run all || true
        continue-on-error: true