on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: Release Drafter
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




permissions:
  contents: read

jobs:
  release-drafter:
    uses: KooshaPari/phenoShared/.github/workflows/reusable-release-drafter.yml@d95bb6755390f73c56ea496b246d098fbf97bbe9
    permissions:
      contents: write
      pull-requests: write
