use crate::lang::{is_core_lang, is_edge_lang, normalize_lang};
use crate::registry::{
    adjacent_domains, domain_owns, domain_title, edge_lang_label, format_lang, repo_url,
    DomainRole, DomainRolesRegistry,
};

const STACK_POLICY_URL: &str =
    "https://github.com/KooshaPari/phenotype-registry/blob/main/docs/rationalization/STACK_POLICY.md";
const DOMAIN_ROLES_URL: &str =
    "https://github.com/KooshaPari/phenotype-registry/blob/main/docs/rationalization/DOMAIN_ROLES.md";

pub fn render_boundary(
    domain: &DomainRole,
    registry: &DomainRolesRegistry,
    lang: &str,
    justify: Option<&str>,
) -> String {
    let title = domain_title(&domain.id);
    let status_line = match domain.status.as_deref() {
        Some("archived") => {
            let successor = domain.successor.as_deref().unwrap_or("see DOMAIN_ROLES.md");
            format!("**Status:** ARCHIVED — successor: {successor}")
        }
        _ => "**Status:** ACTIVE".to_string(),
    };

    let mut out = String::new();
    out.push_str(&format!("# Boundary Lock: {title}\n\n"));
    out.push_str(&format!("{status_line}\n\n"));
    out.push_str(&format!(
        "**Canonical repo:** [{repo}]({url})\n\n",
        repo = domain.repo,
        url = repo_url(&domain.repo),
    ));
    out.push_str("## Owns\n");
    for bullet in domain_owns(&domain.id) {
        out.push_str(&format!("- {bullet}\n"));
    }

    out.push_str("\n## Does NOT own (domain SDKs — install separately)\n");
    for other in adjacent_domains(registry, &domain.id) {
        let other_title = domain_title(&other.id);
        out.push_str(&format!(
            "- {other_title} → [`{repo}`]({url})\n",
            repo = other.repo,
            url = repo_url(&other.repo),
        ));
    }

    out.push_str("\n## Preferred core lang\n");
    let norm = normalize_lang(lang);
    let selected = norm.as_str();
    if is_core_lang(selected) {
        out.push_str(&format!(
            "- **{lang}** (Core tier per [STACK_POLICY]({STACK_POLICY_URL}))\n",
            lang = format_lang(selected),
        ));
    } else if is_edge_lang(selected) {
        out.push_str(&format!(
            "- **{lang}** (Edge tier — justification required per [STACK_POLICY]({STACK_POLICY_URL}))\n",
            lang = format_lang(selected),
        ));
        if let Some(text) = justify {
            out.push_str(&crate::lang::render_edge_justification(selected, text));
        }
    } else {
        match domain.core_lang.as_deref() {
            Some(core) => {
                out.push_str(&format!(
                    "- **{lang}** (Core tier per [STACK_POLICY]({STACK_POLICY_URL}))\n",
                    lang = format_lang(core),
                ));
            }
            None => {
                out.push_str("- N/A (manifest-only repo)\n");
            }
        }
    }

    out.push_str("\n## Edge langs\n");
    if domain.edge_langs.is_empty() {
        out.push_str("- None by default\n");
    } else {
        for code in &domain.edge_langs {
            let label = edge_lang_label(code);
            out.push_str(&format!(
                "- **{label}** — permitted only with documented justification per STACK_POLICY\n",
            ));
            if domain.justify_required {
                out.push_str(
                    "  - Add an edge-language block using the STACK_POLICY template when edge code is introduced\n",
                );
            }
        }
        out.push_str(&format!(
            "\nEdge justification template ([STACK_POLICY]({STACK_POLICY_URL})):\n\n\
             ```markdown\n\
             ## Edge language: <lang>\n\
             - **Scope:** <paths/packages>\n\
             - **Reason:** <why Core tier is not viable now>\n\
             - **Exit criteria:** <when/how to fold into Core or drop edge>\n\
             - **ADR:** <link or N/A>\n\
             ```\n",
        ));
    }

    out.push_str(&format!(
        "\n---\n\n\
         _Generated by `hexakit init`. Domain roles SSOT: [DOMAIN_ROLES]({DOMAIN_ROLES_URL})._\n",
    ));

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registry::DomainRolesRegistry;

    #[test]
    fn boundary_includes_status_and_stack_policy() {
        let reg = DomainRolesRegistry::bundled().unwrap();
        let domain = reg.find("testing").unwrap();
        let md = render_boundary(domain, &reg, "rust", None);
        assert!(md.contains("**Status:** ACTIVE"));
        assert!(md.contains("## Owns"));
        assert!(md.contains("## Does NOT own"));
        assert!(md.contains("STACK_POLICY"));
        assert!(md.contains("PhenoObservability"));
    }

    #[test]
    fn archived_domain_shows_successor() {
        let reg = DomainRolesRegistry::bundled().unwrap();
        let domain = reg.find("process-mgr").unwrap();
        let md = render_boundary(domain, &reg, "rust", None);
        assert!(md.contains("ARCHIVED"));
        assert!(md.contains("thegent control-plane"));
    }
}
