pub fn render_phenosdk_manifest(extras: &[String]) -> String {
    let mut out = String::from(
        "# phenoSDK extras manifest — opt-in domain packages (not boundary owners)\n\
         # Generated by `hexakit init --extras`\n\n\
         [manifest]\n\
         version = \"0.1.0\"\n\
         authority = \"phenotype-registry/docs/rationalization/DOMAIN_ROLES.md\"\n\n",
    );
    if extras.is_empty() {
        out.push_str("# No extras selected\n");
        return out;
    }
    out.push_str("[extras]\n");
    for name in extras {
        let trimmed = name.trim();
        if trimmed.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "{trimmed} = {{ install_hint = \"see PHENOSDK_MANIFEST.md in phenoShared\" }}\n"
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_extras_block() {
        let md = render_phenosdk_manifest(&["pheno-telemetry".into()]);
        assert!(md.contains("pheno-telemetry"));
        assert!(md.contains("[extras]"));
    }
}
