name: cargo-semver-checks
permissions: read-all

on:
  pull_request:
    paths: ['**/Cargo.toml']
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.1.1
      - uses: obi1kenobi/cargo-semver-checks-action@v2
