name: Fuzzing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    paths:
      - '**.rs'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  cargo-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.1.1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz || true
      - name: Run fuzzing
        run: cargo fuzz run all || true
        continue-on-error: true