name: Fuzzing

on:
  push:
    paths:
      - '**.rs'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  cargo-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz || true
      - name: Run fuzzing
        run: cargo fuzz run all || true
        continue-on-error: true